### ISSUE TITLE
setoolkit solution

### ISSUE THREAD

**Issue by mathush** [mathush/github-slideshow#2]
when i was facing this error?

Traceback (most recent call last):
File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
self.finish_request(request, client_address)
File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.8/socketserver.py", line 720, in init
self.handle()
File "/usr/lib/python3.8/http/server.py", line 427, in handle
self.handle_one_request()
File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
method()
File "/usr/share/set/src/webattack/harvester/harvester.py", line 334, in do_POST
filewrite.write(cgi.escape("PARAM: " + line + "\n"))
AttributeError: module 'cgi' has no attribute 'escape'

solution this error to setoolkit 8.0.3 first to go to this directory
/usr/share/setoolkit/src/webattack/harvester# gedit harvester.py

step 1

2 import subprocess
3 import sys
4 import os
5 import re
6 import gic to change "import html"

setp 2

filewrite.write(gic.escape("PARAM: " + line + "\n"))
to change like this

334 filewrite.write(html.escape("PARAM: " + line + "\n"))

i hope you enjoy..

**Comment by madafaka221** [comment]
hello i follow your step but the password not show

**Comment by madafaka221** [comment]
![Screenshot from 2020-07-16 03-04-54](https://user-images.githubusercontent.com/68368001/87638218-fa243780-c775-11ea-95d3-ce18b1e3b3bc.png)
